name: benchmark

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  NUGET_XMLDOC_MODE: skip
  TERM: xterm

on:
  push:
    branches:
      - main
      - dotnet-vnext
      - dotnet-nightly
    paths-ignore:
      - '**/*.gitattributes'
      - '**/*.gitignore'
      - '**/*.md'
  schedule:
    - cron: '0 1 * * MON-FRI'
  workflow_dispatch:

permissions: {}

jobs:
  benchmark:
    name: benchmark
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0

    - name: Run benchmarks
      shell: pwsh
      run: ./benchmark.ps1

    - name: Publish BenchmarkDotNet artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: ${{ !cancelled() }}
      with:
        name: artifacts
        path: ./BenchmarkDotNet.Artifacts/results/*
        if-no-files-found: error

    - name: Get repository name
      id: get-repo-name
      shell: pwsh
      run: |
        $repoName = ${env:GITHUB_REPOSITORY}.Split("/")[-1]
        "repo-name=${repoName}" >> ${env:GITHUB_OUTPUT}

    - name: Publish results
      uses: martincostello/benchmarkdotnet-results-publisher@8ec1d7f1ee9854674aabb3f2b06a5afae1bec8ae # v2.0.1
      with:
        branch: ${{ github.ref_name }}
        comment-on-threshold: true
        output-file-path: '${{ steps.get-repo-name.outputs.repo-name }}/data.json'
        repo: '${{ github.repository_owner }}/benchmarks'
        repo-token: ${{ secrets.BENCHMARKS_TOKEN }}
